### ISSUE TITLE
Can not use this plugin

### ISSUE THREAD

**Issue by GarryXia** [lishaobos/vue-custom-barrage#1]
Could not find a declaration file for module 'vue-custom-barrage'.

**Comment by lishaobos** [comment]
i forgot the declaration file, i will do it.

**Comment by lishaobos** [comment]
can i get your vue version?

**Comment by lishaobos** [comment]
i am finished, you shlould exec npm i vue-custom-barrage@latest

**Comment by lishaobos** [comment]
> Could not find a declaration file for module 'vue-custom-barrage'.

i am finished, you shlould exec npm i vue-custom-barrage@latest

**Comment by lishaobos** [comment]
resolved
