### ISSUE TITLE
页面空，什么都没有

### ISSUE THREAD

**Issue by MrBeiMeng** [lishaobos/vue-custom-barrage#2]
# 我按照案例使用了代码，但是什么都么得

![image](https://user-images.githubusercontent.com/97774172/178110129-4651a6be-90d8-45f2-938d-f803af4095fa.png)

> 我不知道是什么原因。因为也没什么提示。

**Comment by lishaobos** [comment]
> # 我按照案例使用了代码，但是什么都么得
> ![image](https://user-images.githubusercontent.com/97774172/178110129-4651a6be-90d8-45f2-938d-f803af4095fa.png)
> 
> > 我不知道是什么原因。因为也没什么提示。

有可以复现的 git 仓库嘛

**Comment by MrBeiMeng** [comment]
有的，在这个仓库。

`https://github.com/MrBeiMeng/book_manage_keshe.git`

我想在homeView 上面做一个弹幕大屏的效果。但是连example 也没跑通

没想到能回，太顶了！

**Comment by lishaobos** [comment]
> 有的，在这个仓库。
> 
> `https://github.com/MrBeiMeng/book_manage_keshe.git`
> 
> 我想在homeView 上面做一个弹幕大屏的效果。但是连example 也没跑通
> 
> 没想到能回，太顶了！

你好，我没找到任何关于弹幕的代码，有提交代码吗？

**Comment by MrBeiMeng** [comment]
那个，我昨天没跑通，就没提交。也没啥代码。就是复制的你项目的readme 例子

**Comment by MrBeiMeng** [comment]
![image](https://user-images.githubusercontent.com/97774172/178135960-04e66e6e-e6b8-414f-a92a-5f8d1b0380b0.png)

我想加在这里。你有什么建议吗.

**Comment by MrBeiMeng** [comment]
我昨天是在main.js 中注入。在homeView 导入。粘贴你的代码。但是不论是简单案例还是复杂案例都没有任何显示。

**Comment by lishaobos** [comment]
> 我昨天是在main.js 中注入。在homeView 导入。粘贴你的代码。但是不论是简单案例还是复杂案例都没有任何显示。

你好，是这个元素没有设置高度，所以展示不出来，我完善一下我的文档。

![image](https://user-images.githubusercontent.com/46661044/178136076-23148117-e88d-473f-a47b-be473176e103.png)
![image](https://user-images.githubusercontent.com/46661044/178136084-409569a7-9928-4afe-b801-3dcbbe12ace7.png)

**Comment by MrBeiMeng** [comment]
好的嘞。顶！

**Comment by lishaobos** [comment]
已经解决。
